debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.board.board_java: debug,
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: jdbc:mysql://rds-mysql.cvewupsq1piq.ap-northeast-2.rds.amazonaws.com:3306/MYSQL_DB
    username: wonjun
    password: ekdud0822
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

  data.rest:
    base-path: /api
    detection-strategy: annotated
---
  
---