debug: false
management:
  endpoints:
    web:
      exposure:
        include: *

logging:
  level:
    com.board.board_java: debug,
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: jdbc:mysql://rds-mysql.cvewupsq1piq.ap-northeast-2.rds.amazonaws.com:3306/MYSQL_DB_JAVA
    username: wonjun
    password: ekdud0822
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always

  server.http2.enable: true

springdoc:
  enable-data-rest: false
  swagger-ui:
    version: 1.0

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa # Token 암복호화 키

---

---
