name: aws_ec2_docker to Springboot

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/board_java
  IMAGE_TAG: 1.0.${{ github.run_number }}
  NAME: board_java

permissions:
  contents: read
  packages: write

# 빌드 Job
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      
      # JDK version 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # jdk를 제공하는 vender사 이름 ex. zulu, adopt, microsoft
          
      # gradlew 권한 추가
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew
        
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.ACCESS_TOKEN }}

